-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 16:07:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imdb_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imdb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdb_db` DEFAULT CHARACTER SET utf8 ;
USE `imdb_db` ;

-- -----------------------------------------------------
-- Table `imdb_db`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Language` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Language` (
                                                    `LanguageID` INT NOT NULL AUTO_INCREMENT,
                                                    `Language` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`LanguageID`),
    UNIQUE INDEX `LanguageID_UNIQUE` (`LanguageID` ASC) VISIBLE,
    UNIQUE INDEX `Language_UNIQUE` (`Language` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`ProductionCompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`ProductionCompany` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`ProductionCompany` (
                                                             `ProductionCompanyID` INT NOT NULL AUTO_INCREMENT,
                                                             `CompanyName` VARCHAR(100) NOT NULL,
    `Headquarters` VARCHAR(100) NOT NULL,
    `Founded Date` DATE NOT NULL,
    PRIMARY KEY (`ProductionCompanyID`),
    UNIQUE INDEX `ProductionCompanyID_UNIQUE` (`ProductionCompanyID` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Genre` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Genre` (
                                                 `GenreID` INT NOT NULL AUTO_INCREMENT,
                                                 `Name` VARCHAR(100) NOT NULL,
    `Description` VARCHAR(160) NULL,
    PRIMARY KEY (`GenreID`),
    UNIQUE INDEX `GenreID_UNIQUE` (`GenreID` ASC) VISIBLE,
    UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Movie` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Movie` (
                                                 `MovieID` INT NOT NULL AUTO_INCREMENT,
                                                 `Title` VARCHAR(200) NOT NULL,
    `ReleaseDate` DATE NOT NULL,
    `Runtime` TIME NOT NULL,
    `Revenue` FLOAT NOT NULL,
    `MaturityRating` CHAR(10) NOT NULL,
    `ProductionCompanyID` INT NOT NULL,
    `LanguageID` INT NOT NULL,
    `GenreID` INT NOT NULL,
    PRIMARY KEY (`MovieID`),
    UNIQUE INDEX `MovieId_UNIQUE` (`MovieID` ASC) VISIBLE,
    INDEX `MovieLanguage_idx` (`LanguageID` ASC) VISIBLE,
    INDEX `fk_movie_production_company_idx` (`ProductionCompanyID` ASC) VISIBLE,
    INDEX `fk_movie_genre_idx` (`GenreID` ASC) VISIBLE,
    CONSTRAINT `fk_language_movie`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `imdb_db`.`Language` (`LanguageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_productioncompany_movie`
    FOREIGN KEY (`ProductionCompanyID`)
    REFERENCES `imdb_db`.`ProductionCompany` (`ProductionCompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_genre_movie`
    FOREIGN KEY (`GenreID`)
    REFERENCES `imdb_db`.`Genre` (`GenreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Show`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Show` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Show` (
                                                `ShowID` INT NOT NULL AUTO_INCREMENT,
                                                `Title` VARCHAR(200) NOT NULL,
    `ReleaseDate` DATE NOT NULL,
    `EndDate` DATE NULL,
    `MaturityRating` CHAR(10) NOT NULL,
    `ProductionCompanyID` INT NOT NULL,
    `LanguageID` INT NOT NULL,
    `GenreID` INT NOT NULL,
    PRIMARY KEY (`ShowID`),
    UNIQUE INDEX `ShowID_UNIQUE` (`ShowID` ASC) VISIBLE,
    INDEX `fk_show_productioncompany_idx` (`ProductionCompanyID` ASC) VISIBLE,
    INDEX `fk_show_language_idx` (`LanguageID` ASC) VISIBLE,
    INDEX `fk_show_genre_idx` (`GenreID` ASC) VISIBLE,
    CONSTRAINT `fk_productioncompany_show`
    FOREIGN KEY (`ProductionCompanyID`)
    REFERENCES `imdb_db`.`ProductionCompany` (`ProductionCompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_language_show`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `imdb_db`.`Language` (`LanguageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_genre_show`
    FOREIGN KEY (`GenreID`)
    REFERENCES `imdb_db`.`Genre` (`GenreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Person` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Person` (
                                                  `PersonID` INT NOT NULL AUTO_INCREMENT,
                                                  `ShowID` INT NULL,
                                                  `MovieID` INT NULL,
                                                  `Role` VARCHAR(45) NOT NULL,
    `Name` VARCHAR(100) NOT NULL,
    `BornIn` VARCHAR(100) NOT NULL,
    `Birthdate` DATE NOT NULL,
    PRIMARY KEY (`PersonID`),
    UNIQUE INDEX `PersonID_UNIQUE` (`PersonID` ASC) VISIBLE,
    INDEX `fk_show_person_idx` (`ShowID` ASC) VISIBLE,
    INDEX `fk_movie_person_idx` (`MovieID` ASC) VISIBLE,
    CONSTRAINT `fk_show_person`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_movie_person`
    FOREIGN KEY (`MovieID`)
    REFERENCES `imdb_db`.`Movie` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`User` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`User` (
                                                `UserID` INT NOT NULL AUTO_INCREMENT,
                                                `Name` VARCHAR(100) NOT NULL,
    `JoinDate` DATE NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `Birthdate` DATE NULL,
    PRIMARY KEY (`UserID`),
    UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
    UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`News` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`News` (
                                                `NewsID` INT NOT NULL AUTO_INCREMENT,
                                                `ShowID` INT NULL,
                                                `MovieID` INT NULL,
                                                `Category` VARCHAR(50) NOT NULL,
    `Headline` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`NewsID`),
    UNIQUE INDEX `NewsID_UNIQUE` (`NewsID` ASC) VISIBLE,
    INDEX `fk_news_show_idx` (`ShowID` ASC) VISIBLE,
    INDEX `fk_news_movie_idx` (`MovieID` ASC) VISIBLE,
    CONSTRAINT `fk_show_news`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_movie_news`
    FOREIGN KEY (`MovieID`)
    REFERENCES `imdb_db`.`Movie` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Soundtrack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Soundtrack` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Soundtrack` (
                                                      `SoundtrackID` INT NOT NULL AUTO_INCREMENT,
                                                      `MovieID` INT NULL,
                                                      `ShowID` INT NULL,
                                                      `Composer` VARCHAR(100) NOT NULL,
    `Title` VARCHAR(200) NOT NULL,
    `Length` FLOAT NOT NULL,
    PRIMARY KEY (`SoundtrackID`),
    UNIQUE INDEX `SoundtrackID_UNIQUE` (`SoundtrackID` ASC) VISIBLE,
    INDEX `fk_soundtrack_movie_idx` (`MovieID` ASC) VISIBLE,
    INDEX `fk_show_soundtrack_idx` (`ShowID` ASC) VISIBLE,
    CONSTRAINT `fk_movie_soundtrack`
    FOREIGN KEY (`MovieID`)
    REFERENCES `imdb_db`.`Movie` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_show_soundtrack`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Award` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Award` (
                                                 `AwardID` INT NOT NULL AUTO_INCREMENT,
                                                 `SoundtrackID` INT NULL,
                                                 `PersonID` INT NULL,
                                                 `AwardName` VARCHAR(100) NOT NULL,
    `YearReceived` YEAR NOT NULL,
    `Category` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`AwardID`),
    UNIQUE INDEX `AwardID_UNIQUE` (`AwardID` ASC) VISIBLE,
    INDEX `fk_person_award_idx` (`PersonID` ASC) VISIBLE,
    INDEX `fk_soundtrack_award_idx` (`SoundtrackID` ASC) VISIBLE,
    CONSTRAINT `fk_person_award`
    FOREIGN KEY (`PersonID`)
    REFERENCES `imdb_db`.`Person` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_soundtrack_award`
    FOREIGN KEY (`SoundtrackID`)
    REFERENCES `imdb_db`.`Soundtrack` (`SoundtrackID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Review` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Review` (
                                                  `ReviewID` INT NOT NULL AUTO_INCREMENT,
                                                  `MovieID` INT NULL,
                                                  `ShowID` INT NULL,
                                                  `UserID` INT NOT NULL,
                                                  `ReviewContent` VARCHAR(200) NOT NULL,
    `UserRatings` VARCHAR(45) NULL,
    PRIMARY KEY (`ReviewID`, `UserID`),
    UNIQUE INDEX `ReviewID_UNIQUE` (`ReviewID` ASC) VISIBLE,
    INDEX `fk_movie_review_idx` (`MovieID` ASC) VISIBLE,
    INDEX `fk_user_review_idx` (`UserID` ASC) VISIBLE,
    INDEX `fk_show_review_idx` (`ShowID` ASC) VISIBLE,
    CONSTRAINT `fk_movie_review`
    FOREIGN KEY (`MovieID`)
    REFERENCES `imdb_db`.`Movie` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_review`
    FOREIGN KEY (`UserID`)
    REFERENCES `imdb_db`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_show_review`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Trivia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Trivia` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Trivia` (
                                                  `TriviaID` INT NOT NULL AUTO_INCREMENT,
                                                  `MovieID` INT NULL,
                                                  `Question` VARCHAR(100) NOT NULL,
    `Answer` VARCHAR(200) NOT NULL,
    `ShowID` INT NULL,
    PRIMARY KEY (`TriviaID`),
    UNIQUE INDEX `TriviaID_UNIQUE` (`TriviaID` ASC) VISIBLE,
    INDEX `fk_trivia_movie_idx` (`MovieID` ASC) VISIBLE,
    INDEX `fk_show_trivia_idx` (`ShowID` ASC) VISIBLE,
    CONSTRAINT `fk_movie_trivia`
    FOREIGN KEY (`MovieID`)
    REFERENCES `imdb_db`.`Movie` (`MovieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_show_trivia`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`Episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`Episode` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`Episode` (
                                                   `EpisodeID` INT NOT NULL AUTO_INCREMENT,
                                                   `ShowID` INT NOT NULL,
                                                   `SeasonNumber` INT NOT NULL,
                                                   `EpisodeNumber` INT NOT NULL,
                                                   `EpisodeTitle` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`EpisodeID`, `ShowID`),
    UNIQUE INDEX `EpisodeID_UNIQUE` (`EpisodeID` ASC) VISIBLE,
    INDEX `fk_episode_show_idx` (`ShowID` ASC) VISIBLE,
    CONSTRAINT `fk_show_episode`
    FOREIGN KEY (`ShowID`)
    REFERENCES `imdb_db`.`Show` (`ShowID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- SET SQL_MODE = '';
-- DROP USER IF EXISTS imdb_db;
-- SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- CREATE USER 'imdb_db';

-- GRANT ALL ON `imdb_db`.* TO 'imdb_db';
-- GRANT SELECT, INSERT, TRIGGER ON TABLE `imdb_db`.* TO 'imdb_db';
-- GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `imdb_db`.* TO 'imdb_db';
-- GRANT SELECT ON TABLE `imdb_db`.* TO 'imdb_db';
-- GRANT EXECUTE ON ROUTINE `imdb_db`.* TO 'imdb_db';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
